### ISSUE TITLE
photo screen

### ISSUE THREAD

**Issue by ulamnet** [lopspower/DualShot#1]
When ı want take photo not opened screen.

**Comment by ulamnet** [comment]
now backend camera working but frontend not working.

**Comment by lopspower** [comment]
Is the project (as on GitHub) work for you?
Which phone and Android version you test?

**Comment by ulamnet** [comment]
I tested android version : 6 

but how it's work ? in camera not working but backend working.

**Comment by lopspower** [comment]
Show me your stack trace please.

**Comment by ulamnet** [comment]
İn android studio not show stack trace .

**Comment by lopspower** [comment]
You must take the first picture for the camera switches on the front camera.
[Gif example HERE : http://postimg.org/image/6bby33c7j/ ](http://postimg.org/image/6bby33c7j/)

**Comment by ulamnet** [comment]
after backend camera , front camera not opened!

**Comment by ulamnet** [comment]
Already take picture backend camera but after frontend camera not opened.
